{% set name = "limitedinteraction" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/limitedinteraction-{{ version }}.tar.gz
  sha256: ddf05701e3d7bafdb9fc7b742ab2aa9fa092fd6c760898a09d0b2564e5f6524c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - limitedinteraction
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/felixchenier/limitedinteraction
  summary: Provides simple, backend-independant GUI tools for simple user interaction.
  dev_url: https://github.com/felixchenier/limitedinteraction/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
