{% set name = "limitedinteraction" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limitedinteraction-{{ version }}.tar.gz
  sha256: 2014880cfa54dce6a80678822a65498aba43b96a3a0ea2a0a459f1b04312806e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - limitedinteraction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixchenier/limitedinteraction
  summary: Provides simple, backend-independant GUI tools for simple user interaction.
  dev_url: https://github.com/felixchenier/limitedinteraction/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixchenier
