{% set name = "limitedinteraction" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limitedinteraction-{{ version }}.tar.gz
  sha256: be2c9ccccda8bdd5264298132492fb133ad0bc61f374babb0a2fc4dc28d389c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - limitedinteraction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixchenier/limitedinteraction
  summary: Provides simple, backend-independant GUI tools for simple user interaction.
  dev_url: https://github.com/felixchenier/limitedinteraction/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixchenier
