{% set name = "limitedinteraction" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limitedinteraction-{{ version }}.tar.gz
  sha256: 7e5545c8753ed2d7d793c4110bf75bc7696f2a58a99014a117f6a4fee3a3bcec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - limitedinteraction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixchenier/limitedinteraction
  summary: Provides simple, backend-independant GUI tools for simple user interaction.
  dev_url: https://github.com/felixchenier/limitedinteraction/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixchenier
