{% set name = "limitedinteraction" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limitedinteraction-{{ version }}.tar.gz
  sha256: 12d4320eddb9bfcda258269107efe360f8603bdac0a95ad4596da50ab8e8f71e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - limitedinteraction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixchenier/limitedinteraction
  summary: Provides simple, backend-independant GUI tools for simple user interaction.
  dev_url: https://github.com/felixchenier/limitedinteraction/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
